# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contrib/coms/protos/broker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contrib.coms.protos import protocol_pb2 as contrib_dot_coms_dot_protos_dot_protocol__pb2
from contrib.coms.protos import assets_pb2 as contrib_dot_coms_dot_protos_dot_assets__pb2
from contrib.coms.protos import finance_pb2 as contrib_dot_coms_dot_protos_dot_finance__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from contrib.coms.protos import data_bundle_pb2 as contrib_dot_coms_dot_protos_dot_data__bundle__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='contrib/coms/protos/broker.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n contrib/coms/protos/broker.proto\x1a\"contrib/coms/protos/protocol.proto\x1a contrib/coms/protos/assets.proto\x1a!contrib/coms/protos/finance.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a%contrib/coms/protos/data_bundle.proto\"!\n\x0eWarningMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x8b\x02\n\x0bOrderParams\x12*\n\x05style\x18\x01 \x01(\x0e\x32\x1b.OrderParams.ExecutionStyle\x12\x15\n\x05\x61sset\x18\x02 \x01(\x0b\x32\x06.Asset\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x13\n\x0blimit_price\x18\x04 \x01(\x02\x12\x12\n\nstop_price\x18\x05 \x01(\x02\x12\x13\n\x0blimit_order\x18\x06 \x01(\x02\x12\x10\n\x08\x65xchange\x18\x07 \x01(\x02\"Y\n\x0e\x45xecutionStyle\x12\x10\n\x0cMARKET_ORDER\x10\x00\x12\x0f\n\x0bLIMIT_ORDER\x10\x01\x12\x0e\n\nSTOP_ORDER\x10\x02\x12\x14\n\x10STOP_LIMIT_ORDER\x10\x03\"0\n\x10\x42\x61tchOrderParams\x12\x1c\n\x06params\x18\x01 \x03(\x0b\x32\x0c.OrderParams2\xea\x03\n\x06\x42roker\x12#\n\x0bSingleOrder\x12\x0c.OrderParams\x1a\x06.Order\x12\x30\n\x0c\x41\x63\x63ountState\x12\x16.google.protobuf.Empty\x1a\x08.Account\x12\x34\n\x0ePortfolioState\x12\x16.google.protobuf.Empty\x1a\n.Portfolio\x12>\n\x0ePositionsState\x12\x16.google.protobuf.Empty\x1a\x12.AssetPositionPair0\x01\x12(\n\x06Orders\x12\x16.google.protobuf.Empty\x1a\x06.Order\x12\x36\n\x0cTransactions\x12\x16.google.protobuf.Empty\x1a\x0c.Transaction0\x01\x12)\n\nBatchOrder\x12\x11.BatchOrderParams\x1a\x06.Order0\x01\x12-\n\x0b\x43\x61ncelOrder\x12\x06.Order\x1a\x16.google.protobuf.Empty\x12\x32\n\x17\x43\x61ncelAllOrdersForAsset\x12\x06.Asset\x1a\x0f.WarningMessage\x12#\n\rGetDataBundle\x12\x07.Domain\x1a\x07.Bundle0\x01\x62\x06proto3')
  ,
  dependencies=[contrib_dot_coms_dot_protos_dot_protocol__pb2.DESCRIPTOR,contrib_dot_coms_dot_protos_dot_assets__pb2.DESCRIPTOR,contrib_dot_coms_dot_protos_dot_finance__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,contrib_dot_coms_dot_protos_dot_data__bundle__pb2.DESCRIPTOR,])



_ORDERPARAMS_EXECUTIONSTYLE = _descriptor.EnumDescriptor(
  name='ExecutionStyle',
  full_name='OrderParams.ExecutionStyle',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MARKET_ORDER', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIMIT_ORDER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP_ORDER', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP_LIMIT_ORDER', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=423,
  serialized_end=512,
)
_sym_db.RegisterEnumDescriptor(_ORDERPARAMS_EXECUTIONSTYLE)


_WARNINGMESSAGE = _descriptor.Descriptor(
  name='WarningMessage',
  full_name='WarningMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='WarningMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=242,
)


_ORDERPARAMS = _descriptor.Descriptor(
  name='OrderParams',
  full_name='OrderParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='style', full_name='OrderParams.style', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asset', full_name='OrderParams.asset', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='OrderParams.amount', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit_price', full_name='OrderParams.limit_price', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stop_price', full_name='OrderParams.stop_price', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit_order', full_name='OrderParams.limit_order', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='OrderParams.exchange', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ORDERPARAMS_EXECUTIONSTYLE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=512,
)


_BATCHORDERPARAMS = _descriptor.Descriptor(
  name='BatchOrderParams',
  full_name='BatchOrderParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='BatchOrderParams.params', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=514,
  serialized_end=562,
)

_ORDERPARAMS.fields_by_name['style'].enum_type = _ORDERPARAMS_EXECUTIONSTYLE
_ORDERPARAMS.fields_by_name['asset'].message_type = contrib_dot_coms_dot_protos_dot_assets__pb2._ASSET
_ORDERPARAMS_EXECUTIONSTYLE.containing_type = _ORDERPARAMS
_BATCHORDERPARAMS.fields_by_name['params'].message_type = _ORDERPARAMS
DESCRIPTOR.message_types_by_name['WarningMessage'] = _WARNINGMESSAGE
DESCRIPTOR.message_types_by_name['OrderParams'] = _ORDERPARAMS
DESCRIPTOR.message_types_by_name['BatchOrderParams'] = _BATCHORDERPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WarningMessage = _reflection.GeneratedProtocolMessageType('WarningMessage', (_message.Message,), dict(
  DESCRIPTOR = _WARNINGMESSAGE,
  __module__ = 'contrib.coms.protos.broker_pb2'
  # @@protoc_insertion_point(class_scope:WarningMessage)
  ))
_sym_db.RegisterMessage(WarningMessage)

OrderParams = _reflection.GeneratedProtocolMessageType('OrderParams', (_message.Message,), dict(
  DESCRIPTOR = _ORDERPARAMS,
  __module__ = 'contrib.coms.protos.broker_pb2'
  # @@protoc_insertion_point(class_scope:OrderParams)
  ))
_sym_db.RegisterMessage(OrderParams)

BatchOrderParams = _reflection.GeneratedProtocolMessageType('BatchOrderParams', (_message.Message,), dict(
  DESCRIPTOR = _BATCHORDERPARAMS,
  __module__ = 'contrib.coms.protos.broker_pb2'
  # @@protoc_insertion_point(class_scope:BatchOrderParams)
  ))
_sym_db.RegisterMessage(BatchOrderParams)



_BROKER = _descriptor.ServiceDescriptor(
  name='Broker',
  full_name='Broker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=565,
  serialized_end=1055,
  methods=[
  _descriptor.MethodDescriptor(
    name='SingleOrder',
    full_name='Broker.SingleOrder',
    index=0,
    containing_service=None,
    input_type=_ORDERPARAMS,
    output_type=contrib_dot_coms_dot_protos_dot_protocol__pb2._ORDER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AccountState',
    full_name='Broker.AccountState',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=contrib_dot_coms_dot_protos_dot_protocol__pb2._ACCOUNT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PortfolioState',
    full_name='Broker.PortfolioState',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=contrib_dot_coms_dot_protos_dot_protocol__pb2._PORTFOLIO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PositionsState',
    full_name='Broker.PositionsState',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=contrib_dot_coms_dot_protos_dot_protocol__pb2._ASSETPOSITIONPAIR,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Orders',
    full_name='Broker.Orders',
    index=4,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=contrib_dot_coms_dot_protos_dot_protocol__pb2._ORDER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Transactions',
    full_name='Broker.Transactions',
    index=5,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=contrib_dot_coms_dot_protos_dot_finance__pb2._TRANSACTION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='BatchOrder',
    full_name='Broker.BatchOrder',
    index=6,
    containing_service=None,
    input_type=_BATCHORDERPARAMS,
    output_type=contrib_dot_coms_dot_protos_dot_protocol__pb2._ORDER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CancelOrder',
    full_name='Broker.CancelOrder',
    index=7,
    containing_service=None,
    input_type=contrib_dot_coms_dot_protos_dot_protocol__pb2._ORDER,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CancelAllOrdersForAsset',
    full_name='Broker.CancelAllOrdersForAsset',
    index=8,
    containing_service=None,
    input_type=contrib_dot_coms_dot_protos_dot_assets__pb2._ASSET,
    output_type=_WARNINGMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDataBundle',
    full_name='Broker.GetDataBundle',
    index=9,
    containing_service=None,
    input_type=contrib_dot_coms_dot_protos_dot_data__bundle__pb2._DOMAIN,
    output_type=contrib_dot_coms_dot_protos_dot_data__bundle__pb2._BUNDLE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BROKER)

DESCRIPTOR.services_by_name['Broker'] = _BROKER

# @@protoc_insertion_point(module_scope)
