# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contrib/coms/protos/controllable_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contrib.coms.protos import metrics_pb2 as contrib_dot_coms_dot_protos_dot_metrics__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='contrib/coms/protos/controllable_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n.contrib/coms/protos/controllable_service.proto\x1a!contrib/coms/protos/metrics.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9a\x02\n\tRunParams\x12\x14\n\x0c\x63\x61pital_base\x18\x01 \x01(\x02\x12\x31\n\rstart_session\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0b\x65nd_session\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04live\x18\x04 \x01(\x08\x12\x13\n\x0bmetrics_set\x18\x05 \x01(\t\x12\x30\n\x0e\x64\x61ta_frequency\x18\x06 \x01(\x0e\x32\x18.RunParams.DataFrequency\x12\x18\n\x10maximum_leverage\x18\x07 \x01(\t\"$\n\rDataFrequency\x12\n\n\x06MINUTE\x10\x00\x12\x07\n\x03\x44\x41Y\x10\x01\"\xcc\x01\n\x11PerformancePacket\x12+\n\x0f\x63umulative_perf\x18\x01 \x01(\x0b\x32\x12.CumulativeMetrics\x12&\n\ndaily_perf\x18\x02 \x01(\x0b\x32\x12.PeriodPerformance\x12)\n\rminutely_perf\x18\x03 \x01(\x0b\x32\x12.PeriodPerformance\x12\x37\n\x17\x63umulative_risk_metrics\x18\x04 \x01(\x0b\x32\x16.CumulativeRiskMetrics\"x\n\x11PeriodPerformance\x12.\n\x12\x63umulative_metrics\x18\x01 \x01(\x0b\x32\x12.CumulativeMetrics\x12\x33\n\x15period_common_metrics\x18\x02 \x01(\x0b\x32\x14.PeriodCommonMetrics2s\n\x0c\x43ontrollable\x12)\n\x03Run\x12\n.RunParams\x1a\x12.PerformancePacket\"\x00\x30\x01\x12\x38\n\x04Stop\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')
  ,
  dependencies=[contrib_dot_coms_dot_protos_dot_metrics__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])



_RUNPARAMS_DATAFREQUENCY = _descriptor.EnumDescriptor(
  name='DataFrequency',
  full_name='RunParams.DataFrequency',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MINUTE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DAY', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=394,
  serialized_end=430,
)
_sym_db.RegisterEnumDescriptor(_RUNPARAMS_DATAFREQUENCY)


_RUNPARAMS = _descriptor.Descriptor(
  name='RunParams',
  full_name='RunParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='capital_base', full_name='RunParams.capital_base', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_session', full_name='RunParams.start_session', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_session', full_name='RunParams.end_session', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='live', full_name='RunParams.live', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metrics_set', full_name='RunParams.metrics_set', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_frequency', full_name='RunParams.data_frequency', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maximum_leverage', full_name='RunParams.maximum_leverage', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RUNPARAMS_DATAFREQUENCY,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=430,
)


_PERFORMANCEPACKET = _descriptor.Descriptor(
  name='PerformancePacket',
  full_name='PerformancePacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cumulative_perf', full_name='PerformancePacket.cumulative_perf', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='daily_perf', full_name='PerformancePacket.daily_perf', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minutely_perf', full_name='PerformancePacket.minutely_perf', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cumulative_risk_metrics', full_name='PerformancePacket.cumulative_risk_metrics', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=637,
)


_PERIODPERFORMANCE = _descriptor.Descriptor(
  name='PeriodPerformance',
  full_name='PeriodPerformance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cumulative_metrics', full_name='PeriodPerformance.cumulative_metrics', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='period_common_metrics', full_name='PeriodPerformance.period_common_metrics', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=639,
  serialized_end=759,
)

_RUNPARAMS.fields_by_name['start_session'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_RUNPARAMS.fields_by_name['end_session'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_RUNPARAMS.fields_by_name['data_frequency'].enum_type = _RUNPARAMS_DATAFREQUENCY
_RUNPARAMS_DATAFREQUENCY.containing_type = _RUNPARAMS
_PERFORMANCEPACKET.fields_by_name['cumulative_perf'].message_type = contrib_dot_coms_dot_protos_dot_metrics__pb2._CUMULATIVEMETRICS
_PERFORMANCEPACKET.fields_by_name['daily_perf'].message_type = _PERIODPERFORMANCE
_PERFORMANCEPACKET.fields_by_name['minutely_perf'].message_type = _PERIODPERFORMANCE
_PERFORMANCEPACKET.fields_by_name['cumulative_risk_metrics'].message_type = contrib_dot_coms_dot_protos_dot_metrics__pb2._CUMULATIVERISKMETRICS
_PERIODPERFORMANCE.fields_by_name['cumulative_metrics'].message_type = contrib_dot_coms_dot_protos_dot_metrics__pb2._CUMULATIVEMETRICS
_PERIODPERFORMANCE.fields_by_name['period_common_metrics'].message_type = contrib_dot_coms_dot_protos_dot_metrics__pb2._PERIODCOMMONMETRICS
DESCRIPTOR.message_types_by_name['RunParams'] = _RUNPARAMS
DESCRIPTOR.message_types_by_name['PerformancePacket'] = _PERFORMANCEPACKET
DESCRIPTOR.message_types_by_name['PeriodPerformance'] = _PERIODPERFORMANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RunParams = _reflection.GeneratedProtocolMessageType('RunParams', (_message.Message,), dict(
  DESCRIPTOR = _RUNPARAMS,
  __module__ = 'contrib.coms.protos.controllable_service_pb2'
  # @@protoc_insertion_point(class_scope:RunParams)
  ))
_sym_db.RegisterMessage(RunParams)

PerformancePacket = _reflection.GeneratedProtocolMessageType('PerformancePacket', (_message.Message,), dict(
  DESCRIPTOR = _PERFORMANCEPACKET,
  __module__ = 'contrib.coms.protos.controllable_service_pb2'
  # @@protoc_insertion_point(class_scope:PerformancePacket)
  ))
_sym_db.RegisterMessage(PerformancePacket)

PeriodPerformance = _reflection.GeneratedProtocolMessageType('PeriodPerformance', (_message.Message,), dict(
  DESCRIPTOR = _PERIODPERFORMANCE,
  __module__ = 'contrib.coms.protos.controllable_service_pb2'
  # @@protoc_insertion_point(class_scope:PeriodPerformance)
  ))
_sym_db.RegisterMessage(PeriodPerformance)



_CONTROLLABLE = _descriptor.ServiceDescriptor(
  name='Controllable',
  full_name='Controllable',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=761,
  serialized_end=876,
  methods=[
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='Controllable.Run',
    index=0,
    containing_service=None,
    input_type=_RUNPARAMS,
    output_type=_PERFORMANCEPACKET,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Stop',
    full_name='Controllable.Stop',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTROLLABLE)

DESCRIPTOR.services_by_name['Controllable'] = _CONTROLLABLE

# @@protoc_insertion_point(module_scope)
