# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contrib/coms/protos/controllable.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contrib.coms.protos import params_pb2 as contrib_dot_coms_dot_protos_dot_params__pb2
from contrib.coms.protos import metrics_pb2 as contrib_dot_coms_dot_protos_dot_metrics__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='contrib/coms/protos/controllable.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n&contrib/coms/protos/controllable.proto\x1a contrib/coms/protos/params.proto\x1a!contrib/coms/protos/metrics.proto\"\xcc\x01\n\x11PerformancePacket\x12+\n\x0f\x63umulative_perf\x18\x01 \x01(\x0b\x32\x12.CumulativeMetrics\x12&\n\ndaily_perf\x18\x02 \x01(\x0b\x32\x12.PeriodPerformance\x12)\n\rminutely_perf\x18\x03 \x01(\x0b\x32\x12.PeriodPerformance\x12\x37\n\x17\x63umulative_risk_metrics\x18\x04 \x01(\x0b\x32\x16.CumulativeRiskMetrics\"x\n\x11PeriodPerformance\x12.\n\x12\x63umulative_metrics\x18\x01 \x01(\x0b\x32\x12.CumulativeMetrics\x12\x33\n\x15period_common_metrics\x18\x02 \x01(\x0b\x32\x14.PeriodCommonMetrics29\n\x0c\x43ontrollable\x12)\n\x03Run\x12\n.RunParams\x1a\x12.PerformancePacket\"\x00\x30\x01\x62\x06proto3')
  ,
  dependencies=[contrib_dot_coms_dot_protos_dot_params__pb2.DESCRIPTOR,contrib_dot_coms_dot_protos_dot_metrics__pb2.DESCRIPTOR,])




_PERFORMANCEPACKET = _descriptor.Descriptor(
  name='PerformancePacket',
  full_name='PerformancePacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cumulative_perf', full_name='PerformancePacket.cumulative_perf', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='daily_perf', full_name='PerformancePacket.daily_perf', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minutely_perf', full_name='PerformancePacket.minutely_perf', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cumulative_risk_metrics', full_name='PerformancePacket.cumulative_risk_metrics', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=316,
)


_PERIODPERFORMANCE = _descriptor.Descriptor(
  name='PeriodPerformance',
  full_name='PeriodPerformance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cumulative_metrics', full_name='PeriodPerformance.cumulative_metrics', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='period_common_metrics', full_name='PeriodPerformance.period_common_metrics', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=438,
)

_PERFORMANCEPACKET.fields_by_name['cumulative_perf'].message_type = contrib_dot_coms_dot_protos_dot_metrics__pb2._CUMULATIVEMETRICS
_PERFORMANCEPACKET.fields_by_name['daily_perf'].message_type = _PERIODPERFORMANCE
_PERFORMANCEPACKET.fields_by_name['minutely_perf'].message_type = _PERIODPERFORMANCE
_PERFORMANCEPACKET.fields_by_name['cumulative_risk_metrics'].message_type = contrib_dot_coms_dot_protos_dot_metrics__pb2._CUMULATIVERISKMETRICS
_PERIODPERFORMANCE.fields_by_name['cumulative_metrics'].message_type = contrib_dot_coms_dot_protos_dot_metrics__pb2._CUMULATIVEMETRICS
_PERIODPERFORMANCE.fields_by_name['period_common_metrics'].message_type = contrib_dot_coms_dot_protos_dot_metrics__pb2._PERIODCOMMONMETRICS
DESCRIPTOR.message_types_by_name['PerformancePacket'] = _PERFORMANCEPACKET
DESCRIPTOR.message_types_by_name['PeriodPerformance'] = _PERIODPERFORMANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PerformancePacket = _reflection.GeneratedProtocolMessageType('PerformancePacket', (_message.Message,), dict(
  DESCRIPTOR = _PERFORMANCEPACKET,
  __module__ = 'contrib.coms.protos.controllable_pb2'
  # @@protoc_insertion_point(class_scope:PerformancePacket)
  ))
_sym_db.RegisterMessage(PerformancePacket)

PeriodPerformance = _reflection.GeneratedProtocolMessageType('PeriodPerformance', (_message.Message,), dict(
  DESCRIPTOR = _PERIODPERFORMANCE,
  __module__ = 'contrib.coms.protos.controllable_pb2'
  # @@protoc_insertion_point(class_scope:PeriodPerformance)
  ))
_sym_db.RegisterMessage(PeriodPerformance)



_CONTROLLABLE = _descriptor.ServiceDescriptor(
  name='Controllable',
  full_name='Controllable',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=440,
  serialized_end=497,
  methods=[
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='Controllable.Run',
    index=0,
    containing_service=None,
    input_type=contrib_dot_coms_dot_protos_dot_params__pb2._RUNPARAMS,
    output_type=_PERFORMANCEPACKET,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTROLLABLE)

DESCRIPTOR.services_by_name['Controllable'] = _CONTROLLABLE

# @@protoc_insertion_point(module_scope)
