# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contrib/coms/protos/controllable_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from contrib.coms.protos import data_bundle_pb2 as contrib_dot_coms_dot_protos_dot_data__bundle__pb2
from contrib.coms.protos import controller_service_pb2 as contrib_dot_coms_dot_protos_dot_controller__service__pb2
from contrib.coms.protos import broker_pb2 as contrib_dot_coms_dot_protos_dot_broker__pb2
from contrib.control.clock import clock_pb2 as contrib_dot_control_dot_clock_dot_clock__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='contrib/coms/protos/controllable_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n.contrib/coms/protos/controllable_service.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a%contrib/coms/protos/data_bundle.proto\x1a,contrib/coms/protos/controller_service.proto\x1a contrib/coms/protos/broker.proto\x1a!contrib/control/clock/clock.proto2\xeb\x02\n\x0c\x43ontrollable\x12\x34\n\x11ReceiveDataBundle\x12\x07.Bundle\x1a\x16.google.protobuf.Empty\x12\x32\n\x0b\x43lockUpdate\x12\x0b.ClockEvent\x1a\x16.google.protobuf.Empty\x12\x44\n\x10UpdateParameters\x12\x18.ParametersUpdateMessage\x1a\x16.google.protobuf.Empty\x12\x38\n\nInitialize\x12\x12.InitialParameters\x1a\x16.google.protobuf.Empty\x12\x34\n\x0cUpdateBroker\x12\x0c.BrokerState\x1a\x16.google.protobuf.Empty\x12;\n\x0eUpdateCalendar\x12\x11.CalendarMetadata\x1a\x16.google.protobuf.Emptyb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,contrib_dot_coms_dot_protos_dot_data__bundle__pb2.DESCRIPTOR,contrib_dot_coms_dot_protos_dot_controller__service__pb2.DESCRIPTOR,contrib_dot_coms_dot_protos_dot_broker__pb2.DESCRIPTOR,contrib_dot_control_dot_clock_dot_clock__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CONTROLLABLE = _descriptor.ServiceDescriptor(
  name='Controllable',
  full_name='Controllable',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=234,
  serialized_end=597,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReceiveDataBundle',
    full_name='Controllable.ReceiveDataBundle',
    index=0,
    containing_service=None,
    input_type=contrib_dot_coms_dot_protos_dot_data__bundle__pb2._BUNDLE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ClockUpdate',
    full_name='Controllable.ClockUpdate',
    index=1,
    containing_service=None,
    input_type=contrib_dot_control_dot_clock_dot_clock__pb2._CLOCKEVENT,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateParameters',
    full_name='Controllable.UpdateParameters',
    index=2,
    containing_service=None,
    input_type=contrib_dot_coms_dot_protos_dot_controller__service__pb2._PARAMETERSUPDATEMESSAGE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Initialize',
    full_name='Controllable.Initialize',
    index=3,
    containing_service=None,
    input_type=contrib_dot_coms_dot_protos_dot_controller__service__pb2._INITIALPARAMETERS,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateBroker',
    full_name='Controllable.UpdateBroker',
    index=4,
    containing_service=None,
    input_type=contrib_dot_coms_dot_protos_dot_broker__pb2._BROKERSTATE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateCalendar',
    full_name='Controllable.UpdateCalendar',
    index=5,
    containing_service=None,
    input_type=contrib_dot_control_dot_clock_dot_clock__pb2._CALENDARMETADATA,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTROLLABLE)

DESCRIPTOR.services_by_name['Controllable'] = _CONTROLLABLE

# @@protoc_insertion_point(module_scope)
