# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from contrib.coms.protos import assets_pb2 as contrib_dot_coms_dot_protos_dot_assets__pb2
from contrib.coms.protos import finance_pb2 as contrib_dot_coms_dot_protos_dot_finance__pb2
from contrib.coms.protos import protocol_pb2 as contrib_dot_coms_dot_protos_dot_protocol__pb2
from contrib.coms.protos import trade_account_pb2 as contrib_dot_coms_dot_protos_dot_trade__account__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class TradeAccountStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SingleOrder = channel.unary_unary(
        '/TradeAccount/SingleOrder',
        request_serializer=contrib_dot_coms_dot_protos_dot_trade__account__pb2.OrderParams.SerializeToString,
        response_deserializer=contrib_dot_coms_dot_protos_dot_protocol__pb2.Order.FromString,
        )
    self.AccountState = channel.unary_unary(
        '/TradeAccount/AccountState',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=contrib_dot_coms_dot_protos_dot_protocol__pb2.Account.FromString,
        )
    self.PortfolioState = channel.unary_unary(
        '/TradeAccount/PortfolioState',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=contrib_dot_coms_dot_protos_dot_protocol__pb2.Portfolio.FromString,
        )
    self.PositionsState = channel.unary_stream(
        '/TradeAccount/PositionsState',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=contrib_dot_coms_dot_protos_dot_protocol__pb2.AssetPositionPair.FromString,
        )
    self.Orders = channel.unary_unary(
        '/TradeAccount/Orders',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=contrib_dot_coms_dot_protos_dot_protocol__pb2.Order.FromString,
        )
    self.Transactions = channel.unary_stream(
        '/TradeAccount/Transactions',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=contrib_dot_coms_dot_protos_dot_finance__pb2.Transaction.FromString,
        )
    self.BatchOrder = channel.stream_stream(
        '/TradeAccount/BatchOrder',
        request_serializer=contrib_dot_coms_dot_protos_dot_trade__account__pb2.BatchOrderParams.SerializeToString,
        response_deserializer=contrib_dot_coms_dot_protos_dot_protocol__pb2.Order.FromString,
        )
    self.CancelOrder = channel.unary_unary(
        '/TradeAccount/CancelOrder',
        request_serializer=contrib_dot_coms_dot_protos_dot_protocol__pb2.Order.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.CancelAllOrdersForAsset = channel.unary_unary(
        '/TradeAccount/CancelAllOrdersForAsset',
        request_serializer=contrib_dot_coms_dot_protos_dot_assets__pb2.Asset.SerializeToString,
        response_deserializer=contrib_dot_coms_dot_protos_dot_trade__account__pb2.WarningMessage.FromString,
        )


class TradeAccountServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SingleOrder(self, request, context):
    """This should encapsulate the set of services available per account...
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AccountState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PortfolioState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PositionsState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Orders(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Transactions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BatchOrder(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CancelOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CancelAllOrdersForAsset(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TradeAccountServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SingleOrder': grpc.unary_unary_rpc_method_handler(
          servicer.SingleOrder,
          request_deserializer=contrib_dot_coms_dot_protos_dot_trade__account__pb2.OrderParams.FromString,
          response_serializer=contrib_dot_coms_dot_protos_dot_protocol__pb2.Order.SerializeToString,
      ),
      'AccountState': grpc.unary_unary_rpc_method_handler(
          servicer.AccountState,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=contrib_dot_coms_dot_protos_dot_protocol__pb2.Account.SerializeToString,
      ),
      'PortfolioState': grpc.unary_unary_rpc_method_handler(
          servicer.PortfolioState,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=contrib_dot_coms_dot_protos_dot_protocol__pb2.Portfolio.SerializeToString,
      ),
      'PositionsState': grpc.unary_stream_rpc_method_handler(
          servicer.PositionsState,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=contrib_dot_coms_dot_protos_dot_protocol__pb2.AssetPositionPair.SerializeToString,
      ),
      'Orders': grpc.unary_unary_rpc_method_handler(
          servicer.Orders,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=contrib_dot_coms_dot_protos_dot_protocol__pb2.Order.SerializeToString,
      ),
      'Transactions': grpc.unary_stream_rpc_method_handler(
          servicer.Transactions,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=contrib_dot_coms_dot_protos_dot_finance__pb2.Transaction.SerializeToString,
      ),
      'BatchOrder': grpc.stream_stream_rpc_method_handler(
          servicer.BatchOrder,
          request_deserializer=contrib_dot_coms_dot_protos_dot_trade__account__pb2.BatchOrderParams.FromString,
          response_serializer=contrib_dot_coms_dot_protos_dot_protocol__pb2.Order.SerializeToString,
      ),
      'CancelOrder': grpc.unary_unary_rpc_method_handler(
          servicer.CancelOrder,
          request_deserializer=contrib_dot_coms_dot_protos_dot_protocol__pb2.Order.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'CancelAllOrdersForAsset': grpc.unary_unary_rpc_method_handler(
          servicer.CancelAllOrdersForAsset,
          request_deserializer=contrib_dot_coms_dot_protos_dot_assets__pb2.Asset.FromString,
          response_serializer=contrib_dot_coms_dot_protos_dot_trade__account__pb2.WarningMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TradeAccount', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
