# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contrib/coms/protos/clock.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='contrib/coms/protos/clock.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1f\x63ontrib/coms/protos/clock.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\r\n\x0bSyncRequest\":\n\tSyncReply\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x0e\n\x0c\x44\x65layRequest\";\n\nDelayReply\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2P\n\x05\x43lock\x12\"\n\x04Sync\x12\x0c.SyncRequest\x1a\n.SyncReply0\x01\x12#\n\x05\x44\x65lay\x12\r.DelayRequest\x1a\x0b.DelayReplyb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_SYNCREQUEST = _descriptor.Descriptor(
  name='SyncRequest',
  full_name='SyncRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=81,
)


_SYNCREPLY = _descriptor.Descriptor(
  name='SyncReply',
  full_name='SyncReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='SyncReply.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=141,
)


_DELAYREQUEST = _descriptor.Descriptor(
  name='DelayRequest',
  full_name='DelayRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=157,
)


_DELAYREPLY = _descriptor.Descriptor(
  name='DelayReply',
  full_name='DelayReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='DelayReply.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=218,
)

_SYNCREPLY.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_DELAYREPLY.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['SyncRequest'] = _SYNCREQUEST
DESCRIPTOR.message_types_by_name['SyncReply'] = _SYNCREPLY
DESCRIPTOR.message_types_by_name['DelayRequest'] = _DELAYREQUEST
DESCRIPTOR.message_types_by_name['DelayReply'] = _DELAYREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SyncRequest = _reflection.GeneratedProtocolMessageType('SyncRequest', (_message.Message,), dict(
  DESCRIPTOR = _SYNCREQUEST,
  __module__ = 'contrib.coms.protos.clock_pb2'
  # @@protoc_insertion_point(class_scope:SyncRequest)
  ))
_sym_db.RegisterMessage(SyncRequest)

SyncReply = _reflection.GeneratedProtocolMessageType('SyncReply', (_message.Message,), dict(
  DESCRIPTOR = _SYNCREPLY,
  __module__ = 'contrib.coms.protos.clock_pb2'
  # @@protoc_insertion_point(class_scope:SyncReply)
  ))
_sym_db.RegisterMessage(SyncReply)

DelayRequest = _reflection.GeneratedProtocolMessageType('DelayRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELAYREQUEST,
  __module__ = 'contrib.coms.protos.clock_pb2'
  # @@protoc_insertion_point(class_scope:DelayRequest)
  ))
_sym_db.RegisterMessage(DelayRequest)

DelayReply = _reflection.GeneratedProtocolMessageType('DelayReply', (_message.Message,), dict(
  DESCRIPTOR = _DELAYREPLY,
  __module__ = 'contrib.coms.protos.clock_pb2'
  # @@protoc_insertion_point(class_scope:DelayReply)
  ))
_sym_db.RegisterMessage(DelayReply)



_CLOCK = _descriptor.ServiceDescriptor(
  name='Clock',
  full_name='Clock',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=220,
  serialized_end=300,
  methods=[
  _descriptor.MethodDescriptor(
    name='Sync',
    full_name='Clock.Sync',
    index=0,
    containing_service=None,
    input_type=_SYNCREQUEST,
    output_type=_SYNCREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delay',
    full_name='Clock.Delay',
    index=1,
    containing_service=None,
    input_type=_DELAYREQUEST,
    output_type=_DELAYREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLOCK)

DESCRIPTOR.services_by_name['Clock'] = _CLOCK

# @@protoc_insertion_point(module_scope)
