# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protos import controller_service_pb2 as contrib_dot_coms_dot_protos_dot_controller__service__pb2
from protos import data_bundle_pb2 as contrib_dot_coms_dot_protos_dot_data__bundle__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ControllerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Deploy = channel.unary_unary(
        '/Controller/Deploy',
        request_serializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.Strategy.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.GetEnvironment = channel.unary_unary(
        '/Controller/GetEnvironment',
        request_serializer=contrib_dot_coms_dot_protos_dot_data__bundle__pb2.Domain.SerializeToString,
        response_deserializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.Environment.FromString,
        )
    self.ReceivePerformancePacket = channel.unary_unary(
        '/Controller/ReceivePerformancePacket',
        request_serializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.PerformancePacket.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Stop = channel.stream_unary(
        '/Controller/Stop',
        request_serializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.ID.SerializeToString,
        response_deserializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.StopStatus.FromString,
        )
    self.Liquidate = channel.stream_unary(
        '/Controller/Liquidate',
        request_serializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.ID.SerializeToString,
        response_deserializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.LiquidationStatus.FromString,
        )
    self.Run = channel.unary_stream(
        '/Controller/Run',
        request_serializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.RunParams.SerializeToString,
        response_deserializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.PerformancePacket.FromString,
        )
    self.StrategyList = channel.unary_stream(
        '/Controller/StrategyList',
        request_serializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.Filter.SerializeToString,
        response_deserializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.Metadata.FromString,
        )
    self.AssignCapital = channel.stream_unary(
        '/Controller/AssignCapital',
        request_serializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.CapitalAssignment.SerializeToString,
        response_deserializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.CapitalAssignmentStatus.FromString,
        )
    self.GetDataBundle = channel.unary_unary(
        '/Controller/GetDataBundle',
        request_serializer=contrib_dot_coms_dot_protos_dot_data__bundle__pb2.Domain.SerializeToString,
        response_deserializer=contrib_dot_coms_dot_protos_dot_data__bundle__pb2.Bundle.FromString,
        )


class ControllerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Deploy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetEnvironment(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReceivePerformancePacket(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Stop(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Liquidate(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Run(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StrategyList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AssignCapital(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDataBundle(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ControllerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Deploy': grpc.unary_unary_rpc_method_handler(
          servicer.Deploy,
          request_deserializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.Strategy.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'GetEnvironment': grpc.unary_unary_rpc_method_handler(
          servicer.GetEnvironment,
          request_deserializer=contrib_dot_coms_dot_protos_dot_data__bundle__pb2.Domain.FromString,
          response_serializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.Environment.SerializeToString,
      ),
      'ReceivePerformancePacket': grpc.unary_unary_rpc_method_handler(
          servicer.ReceivePerformancePacket,
          request_deserializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.PerformancePacket.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Stop': grpc.stream_unary_rpc_method_handler(
          servicer.Stop,
          request_deserializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.ID.FromString,
          response_serializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.StopStatus.SerializeToString,
      ),
      'Liquidate': grpc.stream_unary_rpc_method_handler(
          servicer.Liquidate,
          request_deserializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.ID.FromString,
          response_serializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.LiquidationStatus.SerializeToString,
      ),
      'Run': grpc.unary_stream_rpc_method_handler(
          servicer.Run,
          request_deserializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.RunParams.FromString,
          response_serializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.PerformancePacket.SerializeToString,
      ),
      'StrategyList': grpc.unary_stream_rpc_method_handler(
          servicer.StrategyList,
          request_deserializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.Filter.FromString,
          response_serializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.Metadata.SerializeToString,
      ),
      'AssignCapital': grpc.stream_unary_rpc_method_handler(
          servicer.AssignCapital,
          request_deserializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.CapitalAssignment.FromString,
          response_serializer=contrib_dot_coms_dot_protos_dot_controller__service__pb2.CapitalAssignmentStatus.SerializeToString,
      ),
      'GetDataBundle': grpc.unary_unary_rpc_method_handler(
          servicer.GetDataBundle,
          request_deserializer=contrib_dot_coms_dot_protos_dot_data__bundle__pb2.Domain.FromString,
          response_serializer=contrib_dot_coms_dot_protos_dot_data__bundle__pb2.Bundle.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Controller', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
