# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from protos import clock_pb2 as protos_dot_clock__pb2
from protos import controller_pb2 as protos_dot_controller__pb2
from protos import data_pb2 as protos_dot_data__pb2


class ControllableStub(object):
  """TODO: State: bytes...

  A service to be controller by a controller service
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.update_data_bundle = channel.stream_unary(
        '/Controllable/update_data_bundle',
        request_serializer=protos_dot_data__pb2.Data.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.update_parameters = channel.unary_unary(
        '/Controllable/update_parameters',
        request_serializer=protos_dot_controller__pb2.ParametersUpdateRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.initialize = channel.stream_unary(
        '/Controllable/initialize',
        request_serializer=protos_dot_data__pb2.Data.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.clock_update = channel.unary_unary(
        '/Controllable/clock_update',
        request_serializer=protos_dot_clock__pb2.ClockEvent.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.update_account = channel.stream_unary(
        '/Controllable/update_account',
        request_serializer=protos_dot_data__pb2.Data.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.update_calendar = channel.stream_unary(
        '/Controllable/update_calendar',
        request_serializer=protos_dot_data__pb2.Data.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.stop = channel.unary_stream(
        '/Controllable/stop',
        request_serializer=protos_dot_controller__pb2.StopParams.SerializeToString,
        response_deserializer=protos_dot_data__pb2.Data.FromString,
        )


class ControllableServicer(object):
  """TODO: State: bytes...

  A service to be controller by a controller service
  """

  def update_data_bundle(self, request_iterator, context):
    """the controller calls this method to send a data bundle to the controllable
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def update_parameters(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def initialize(self, request_iterator, context):
    """called to initialize the controllable (sends initparams)
    (strategy etc.)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def clock_update(self, request, context):
    """TODO: should return the state of the strategy run session at each update...
    update sends an UpdateRequest. since this could get arbitrarily big, we send it
    in chunks of bytes.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def update_account(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def update_calendar(self, request_iterator, context):
    """receives periodic calendar updates
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def stop(self, request, context):
    """TODO: should return the state of the controllable after it stopped...
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ControllableServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'update_data_bundle': grpc.stream_unary_rpc_method_handler(
          servicer.update_data_bundle,
          request_deserializer=protos_dot_data__pb2.Data.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'update_parameters': grpc.unary_unary_rpc_method_handler(
          servicer.update_parameters,
          request_deserializer=protos_dot_controller__pb2.ParametersUpdateRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'initialize': grpc.stream_unary_rpc_method_handler(
          servicer.initialize,
          request_deserializer=protos_dot_data__pb2.Data.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'clock_update': grpc.unary_unary_rpc_method_handler(
          servicer.clock_update,
          request_deserializer=protos_dot_clock__pb2.ClockEvent.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'update_account': grpc.stream_unary_rpc_method_handler(
          servicer.update_account,
          request_deserializer=protos_dot_data__pb2.Data.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'update_calendar': grpc.stream_unary_rpc_method_handler(
          servicer.update_calendar,
          request_deserializer=protos_dot_data__pb2.Data.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'stop': grpc.unary_stream_rpc_method_handler(
          servicer.stop,
          request_deserializer=protos_dot_controller__pb2.StopParams.FromString,
          response_serializer=protos_dot_data__pb2.Data.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Controllable', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
