# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/development.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from protos import data_pb2 as protos_dot_data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/development.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18protos/development.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11protos/data.proto\"4\n\x12NewStrategyRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08universe\x18\x02 \x01(\t\"\'\n\x13NewStrategyResponse\x12\x10\n\x08template\x18\x01 \x01(\x0c\"\x0e\n\x0cPushResponse\"4\n\x0bSaveRequest\x12\x13\n\x0bstrategy_id\x18\x01 \x01(\t\x12\x10\n\x08strategy\x18\x02 \x01(\x0c\"\x0e\n\x0cSaveResponse\"&\n\x0fStrategyRequest\x12\x13\n\x0bstrategy_id\x18\x01 \x01(\t\"\xdb\x01\n\x0cSetupRequest\x12\x13\n\x0bstrategy_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61pital\x18\x07 \x01(\x02\x12\x14\n\x0cmax_leverage\x18\x08 \x01(\x02\x12\x10\n\x08universe\x18\x02 \x01(\t\x12\x11\n\tlook_back\x18\x05 \x01(\x05\x12\x16\n\x0e\x64\x61ta_frequency\x18\x06 \x01(\t\x12)\n\x05start\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03\x65nd\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"#\n\rSetupResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\"#\n\rDeleteRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\x10\n\x0e\x44\x65leteResponse2\x9b\x01\n\x06\x45\x64itor\x12$\n\x03New\x12\x13.NewStrategyRequest\x1a\x06.Chunk0\x01\x12\x1f\n\x04Save\x12\x06.Chunk\x1a\r.SaveResponse(\x01\x12\x1f\n\x04Push\x12\x06.Chunk\x1a\r.PushResponse(\x01\x12)\n\x0bGetStrategy\x12\x10.StrategyRequest\x1a\x06.Chunk0\x01\x32`\n\x0b\x45nvironment\x12&\n\x05Setup\x12\r.SetupRequest\x1a\x0e.SetupResponse\x12)\n\x06\x44\x65lete\x12\x0e.DeleteRequest\x1a\x0f.DeleteResponseb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,protos_dot_data__pb2.DESCRIPTOR,])




_NEWSTRATEGYREQUEST = _descriptor.Descriptor(
  name='NewStrategyRequest',
  full_name='NewStrategyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='NewStrategyRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='universe', full_name='NewStrategyRequest.universe', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=132,
)


_NEWSTRATEGYRESPONSE = _descriptor.Descriptor(
  name='NewStrategyResponse',
  full_name='NewStrategyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template', full_name='NewStrategyResponse.template', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=173,
)


_PUSHRESPONSE = _descriptor.Descriptor(
  name='PushResponse',
  full_name='PushResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=189,
)


_SAVEREQUEST = _descriptor.Descriptor(
  name='SaveRequest',
  full_name='SaveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='strategy_id', full_name='SaveRequest.strategy_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strategy', full_name='SaveRequest.strategy', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=243,
)


_SAVERESPONSE = _descriptor.Descriptor(
  name='SaveResponse',
  full_name='SaveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=259,
)


_STRATEGYREQUEST = _descriptor.Descriptor(
  name='StrategyRequest',
  full_name='StrategyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='strategy_id', full_name='StrategyRequest.strategy_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=299,
)


_SETUPREQUEST = _descriptor.Descriptor(
  name='SetupRequest',
  full_name='SetupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='strategy_id', full_name='SetupRequest.strategy_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='capital', full_name='SetupRequest.capital', index=1,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_leverage', full_name='SetupRequest.max_leverage', index=2,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='universe', full_name='SetupRequest.universe', index=3,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='look_back', full_name='SetupRequest.look_back', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_frequency', full_name='SetupRequest.data_frequency', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='SetupRequest.start', index=6,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='SetupRequest.end', index=7,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=521,
)


_SETUPRESPONSE = _descriptor.Descriptor(
  name='SetupResponse',
  full_name='SetupResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='SetupResponse.session_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=523,
  serialized_end=558,
)


_DELETEREQUEST = _descriptor.Descriptor(
  name='DeleteRequest',
  full_name='DeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='DeleteRequest.session_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=560,
  serialized_end=595,
)


_DELETERESPONSE = _descriptor.Descriptor(
  name='DeleteResponse',
  full_name='DeleteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=597,
  serialized_end=613,
)

_SETUPREQUEST.fields_by_name['start'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SETUPREQUEST.fields_by_name['end'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['NewStrategyRequest'] = _NEWSTRATEGYREQUEST
DESCRIPTOR.message_types_by_name['NewStrategyResponse'] = _NEWSTRATEGYRESPONSE
DESCRIPTOR.message_types_by_name['PushResponse'] = _PUSHRESPONSE
DESCRIPTOR.message_types_by_name['SaveRequest'] = _SAVEREQUEST
DESCRIPTOR.message_types_by_name['SaveResponse'] = _SAVERESPONSE
DESCRIPTOR.message_types_by_name['StrategyRequest'] = _STRATEGYREQUEST
DESCRIPTOR.message_types_by_name['SetupRequest'] = _SETUPREQUEST
DESCRIPTOR.message_types_by_name['SetupResponse'] = _SETUPRESPONSE
DESCRIPTOR.message_types_by_name['DeleteRequest'] = _DELETEREQUEST
DESCRIPTOR.message_types_by_name['DeleteResponse'] = _DELETERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewStrategyRequest = _reflection.GeneratedProtocolMessageType('NewStrategyRequest', (_message.Message,), dict(
  DESCRIPTOR = _NEWSTRATEGYREQUEST,
  __module__ = 'protos.development_pb2'
  # @@protoc_insertion_point(class_scope:NewStrategyRequest)
  ))
_sym_db.RegisterMessage(NewStrategyRequest)

NewStrategyResponse = _reflection.GeneratedProtocolMessageType('NewStrategyResponse', (_message.Message,), dict(
  DESCRIPTOR = _NEWSTRATEGYRESPONSE,
  __module__ = 'protos.development_pb2'
  # @@protoc_insertion_point(class_scope:NewStrategyResponse)
  ))
_sym_db.RegisterMessage(NewStrategyResponse)

PushResponse = _reflection.GeneratedProtocolMessageType('PushResponse', (_message.Message,), dict(
  DESCRIPTOR = _PUSHRESPONSE,
  __module__ = 'protos.development_pb2'
  # @@protoc_insertion_point(class_scope:PushResponse)
  ))
_sym_db.RegisterMessage(PushResponse)

SaveRequest = _reflection.GeneratedProtocolMessageType('SaveRequest', (_message.Message,), dict(
  DESCRIPTOR = _SAVEREQUEST,
  __module__ = 'protos.development_pb2'
  # @@protoc_insertion_point(class_scope:SaveRequest)
  ))
_sym_db.RegisterMessage(SaveRequest)

SaveResponse = _reflection.GeneratedProtocolMessageType('SaveResponse', (_message.Message,), dict(
  DESCRIPTOR = _SAVERESPONSE,
  __module__ = 'protos.development_pb2'
  # @@protoc_insertion_point(class_scope:SaveResponse)
  ))
_sym_db.RegisterMessage(SaveResponse)

StrategyRequest = _reflection.GeneratedProtocolMessageType('StrategyRequest', (_message.Message,), dict(
  DESCRIPTOR = _STRATEGYREQUEST,
  __module__ = 'protos.development_pb2'
  # @@protoc_insertion_point(class_scope:StrategyRequest)
  ))
_sym_db.RegisterMessage(StrategyRequest)

SetupRequest = _reflection.GeneratedProtocolMessageType('SetupRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETUPREQUEST,
  __module__ = 'protos.development_pb2'
  # @@protoc_insertion_point(class_scope:SetupRequest)
  ))
_sym_db.RegisterMessage(SetupRequest)

SetupResponse = _reflection.GeneratedProtocolMessageType('SetupResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETUPRESPONSE,
  __module__ = 'protos.development_pb2'
  # @@protoc_insertion_point(class_scope:SetupResponse)
  ))
_sym_db.RegisterMessage(SetupResponse)

DeleteRequest = _reflection.GeneratedProtocolMessageType('DeleteRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETEREQUEST,
  __module__ = 'protos.development_pb2'
  # @@protoc_insertion_point(class_scope:DeleteRequest)
  ))
_sym_db.RegisterMessage(DeleteRequest)

DeleteResponse = _reflection.GeneratedProtocolMessageType('DeleteResponse', (_message.Message,), dict(
  DESCRIPTOR = _DELETERESPONSE,
  __module__ = 'protos.development_pb2'
  # @@protoc_insertion_point(class_scope:DeleteResponse)
  ))
_sym_db.RegisterMessage(DeleteResponse)



_EDITOR = _descriptor.ServiceDescriptor(
  name='Editor',
  full_name='Editor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=616,
  serialized_end=771,
  methods=[
  _descriptor.MethodDescriptor(
    name='New',
    full_name='Editor.New',
    index=0,
    containing_service=None,
    input_type=_NEWSTRATEGYREQUEST,
    output_type=protos_dot_data__pb2._CHUNK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Save',
    full_name='Editor.Save',
    index=1,
    containing_service=None,
    input_type=protos_dot_data__pb2._CHUNK,
    output_type=_SAVERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Push',
    full_name='Editor.Push',
    index=2,
    containing_service=None,
    input_type=protos_dot_data__pb2._CHUNK,
    output_type=_PUSHRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetStrategy',
    full_name='Editor.GetStrategy',
    index=3,
    containing_service=None,
    input_type=_STRATEGYREQUEST,
    output_type=protos_dot_data__pb2._CHUNK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EDITOR)

DESCRIPTOR.services_by_name['Editor'] = _EDITOR


_ENVIRONMENT = _descriptor.ServiceDescriptor(
  name='Environment',
  full_name='Environment',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=773,
  serialized_end=869,
  methods=[
  _descriptor.MethodDescriptor(
    name='Setup',
    full_name='Environment.Setup',
    index=0,
    containing_service=None,
    input_type=_SETUPREQUEST,
    output_type=_SETUPRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='Environment.Delete',
    index=1,
    containing_service=None,
    input_type=_DELETEREQUEST,
    output_type=_DELETERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ENVIRONMENT)

DESCRIPTOR.services_by_name['Environment'] = _ENVIRONMENT

# @@protoc_insertion_point(module_scope)
