# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from protos import controller_pb2 as protos_dot_controller__pb2
from protos import data_bundle_pb2 as protos_dot_data__bundle__pb2
from protos import data_pb2 as protos_dot_data__pb2
from protos import hub_pb2 as protos_dot_hub__pb2


class HubStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.UploadGraph = channel.stream_unary(
        '/Hub/UploadGraph',
        request_serializer=protos_dot_data__pb2.Data.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.DownloadGraph = channel.unary_stream(
        '/Hub/DownloadGraph',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=protos_dot_data__pb2.Data.FromString,
        )
    self.GetController = channel.unary_unary(
        '/Hub/GetController',
        request_serializer=protos_dot_controller__pb2.ControllerRequest.SerializeToString,
        response_deserializer=protos_dot_controller__pb2.ControllerReply.FromString,
        )
    self.GetDataBundle = channel.unary_stream(
        '/Hub/GetDataBundle',
        request_serializer=protos_dot_data__bundle__pb2.CompoundDomainDef.SerializeToString,
        response_deserializer=protos_dot_data__pb2.Data.FromString,
        )
    self.Deploy = channel.unary_unary(
        '/Hub/Deploy',
        request_serializer=protos_dot_hub__pb2.DeploymentRequest.SerializeToString,
        response_deserializer=protos_dot_hub__pb2.DeploymentResponse.FromString,
        )


class HubServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def UploadGraph(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DownloadGraph(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetController(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDataBundle(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Deploy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HubServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'UploadGraph': grpc.stream_unary_rpc_method_handler(
          servicer.UploadGraph,
          request_deserializer=protos_dot_data__pb2.Data.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'DownloadGraph': grpc.unary_stream_rpc_method_handler(
          servicer.DownloadGraph,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=protos_dot_data__pb2.Data.SerializeToString,
      ),
      'GetController': grpc.unary_unary_rpc_method_handler(
          servicer.GetController,
          request_deserializer=protos_dot_controller__pb2.ControllerRequest.FromString,
          response_serializer=protos_dot_controller__pb2.ControllerReply.SerializeToString,
      ),
      'GetDataBundle': grpc.unary_stream_rpc_method_handler(
          servicer.GetDataBundle,
          request_deserializer=protos_dot_data__bundle__pb2.CompoundDomainDef.FromString,
          response_serializer=protos_dot_data__pb2.Data.SerializeToString,
      ),
      'Deploy': grpc.unary_unary_rpc_method_handler(
          servicer.Deploy,
          request_deserializer=protos_dot_hub__pb2.DeploymentRequest.FromString,
          response_serializer=protos_dot_hub__pb2.DeploymentResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Hub', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
