# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/hub.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from protos import data_pb2 as protos_dot_data__pb2
from protos import controller_pb2 as protos_dot_controller__pb2
from protos import data_bundle_pb2 as protos_dot_data__bundle__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/hub.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10protos/hub.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x11protos/data.proto\x1a\x17protos/controller.proto\x1a\x18protos/data_bundle.proto\"\x13\n\x11\x44\x65ploymentRequest\"\x14\n\x12\x44\x65ploymentResponse2\xff\x01\n\x03Hub\x12.\n\x0bUploadGraph\x12\x05.Data\x1a\x16.google.protobuf.Empty(\x01\x12\x30\n\rDownloadGraph\x12\x16.google.protobuf.Empty\x1a\x05.Data0\x01\x12\x35\n\rGetController\x12\x12.ControllerRequest\x1a\x10.ControllerReply\x12,\n\rGetDataBundle\x12\x12.CompoundDomainDef\x1a\x05.Data0\x01\x12\x31\n\x06\x44\x65ploy\x12\x12.DeploymentRequest\x1a\x13.DeploymentResponseb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,protos_dot_data__pb2.DESCRIPTOR,protos_dot_controller__pb2.DESCRIPTOR,protos_dot_data__bundle__pb2.DESCRIPTOR,])




_DEPLOYMENTREQUEST = _descriptor.Descriptor(
  name='DeploymentRequest',
  full_name='DeploymentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=138,
)


_DEPLOYMENTRESPONSE = _descriptor.Descriptor(
  name='DeploymentResponse',
  full_name='DeploymentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=160,
)

DESCRIPTOR.message_types_by_name['DeploymentRequest'] = _DEPLOYMENTREQUEST
DESCRIPTOR.message_types_by_name['DeploymentResponse'] = _DEPLOYMENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeploymentRequest = _reflection.GeneratedProtocolMessageType('DeploymentRequest', (_message.Message,), dict(
  DESCRIPTOR = _DEPLOYMENTREQUEST,
  __module__ = 'protos.hub_pb2'
  # @@protoc_insertion_point(class_scope:DeploymentRequest)
  ))
_sym_db.RegisterMessage(DeploymentRequest)

DeploymentResponse = _reflection.GeneratedProtocolMessageType('DeploymentResponse', (_message.Message,), dict(
  DESCRIPTOR = _DEPLOYMENTRESPONSE,
  __module__ = 'protos.hub_pb2'
  # @@protoc_insertion_point(class_scope:DeploymentResponse)
  ))
_sym_db.RegisterMessage(DeploymentResponse)



_HUB = _descriptor.ServiceDescriptor(
  name='Hub',
  full_name='Hub',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=163,
  serialized_end=418,
  methods=[
  _descriptor.MethodDescriptor(
    name='UploadGraph',
    full_name='Hub.UploadGraph',
    index=0,
    containing_service=None,
    input_type=protos_dot_data__pb2._DATA,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DownloadGraph',
    full_name='Hub.DownloadGraph',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=protos_dot_data__pb2._DATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetController',
    full_name='Hub.GetController',
    index=2,
    containing_service=None,
    input_type=protos_dot_controller__pb2._CONTROLLERREQUEST,
    output_type=protos_dot_controller__pb2._CONTROLLERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDataBundle',
    full_name='Hub.GetDataBundle',
    index=3,
    containing_service=None,
    input_type=protos_dot_data__bundle__pb2._COMPOUNDDOMAINDEF,
    output_type=protos_dot_data__pb2._DATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Deploy',
    full_name='Hub.Deploy',
    index=4,
    containing_service=None,
    input_type=_DEPLOYMENTREQUEST,
    output_type=_DEPLOYMENTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HUB)

DESCRIPTOR.services_by_name['Hub'] = _HUB

# @@protoc_insertion_point(module_scope)
