# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/tracker_state.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/tracker_state.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1aprotos/tracker_state.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\\\n\x0cTrackerState\x12\x36\n\x12\x66irst_open_session\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0cledger_state\x18\x02 \x01(\x0c\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_TRACKERSTATE = _descriptor.Descriptor(
  name='TrackerState',
  full_name='TrackerState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_open_session', full_name='TrackerState.first_open_session', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ledger_state', full_name='TrackerState.ledger_state', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=155,
)

_TRACKERSTATE.fields_by_name['first_open_session'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['TrackerState'] = _TRACKERSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrackerState = _reflection.GeneratedProtocolMessageType('TrackerState', (_message.Message,), dict(
  DESCRIPTOR = _TRACKERSTATE,
  __module__ = 'protos.tracker_state_pb2'
  # @@protoc_insertion_point(class_scope:TrackerState)
  ))
_sym_db.RegisterMessage(TrackerState)


# @@protoc_insertion_point(module_scope)
