# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contrib/control/controllable.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from protos import data_bundle_pb2 as contrib_dot_coms_dot_protos_dot_data__bundle__pb2, \
    broker_pb2 as contrib_dot_coms_dot_protos_dot_broker__pb2
from contrib.control import controller_pb2 as contrib_dot_control_dot_controller__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from contrib.control import clock_pb2 as contrib_dot_control_dot_clock__pb2
from contrib.control import data_pb2 as contrib_dot_control_dot_data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='contrib/control/controllable.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\"contrib/control/controllable.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a%contrib/coms/protos/data_bundle.proto\x1a contrib/coms/protos/broker.proto\x1a contrib/control/controller.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1b\x63ontrib/control/clock.proto\x1a\x1a\x63ontrib/control/data.proto\"S\n\nInitParams\x12\"\n\x06\x64omain\x18\x01 \x01(\x0b\x32\x12.CompoundDomainDef\x12\x10\n\x08strategy\x18\x02 \x01(\x0c\x12\x0f\n\x07\x63\x61pital\x18\x03 \x01(\x02\"y\n\rUpdateMessage\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\x05\x65vent\x18\x02 \x01(\x0e\x32\x06.Event\x12\"\n\x0c\x62roker_state\x18\x03 \x01(\x0b\x32\x0c.BrokerState2\xa5\x02\n\x0c\x43ontrollable\x12\x33\n\x10UpdateDataBundle\x12\x05.Data\x1a\x16.google.protobuf.Empty(\x01\x12\x44\n\x10UpdateParameters\x12\x18.ParametersUpdateMessage\x1a\x16.google.protobuf.Empty\x12-\n\nInitialize\x12\x05.Data\x1a\x16.google.protobuf.Empty(\x01\x12\x1a\n\x06Update\x12\x05.Data\x1a\x05.Data(\x01\x30\x01\x12\x31\n\x0eUpdateCalendar\x12\x05.Data\x1a\x16.google.protobuf.Empty(\x01\x12\x1c\n\x04Stop\x12\x0b.StopParams\x1a\x05.Data0\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,contrib_dot_coms_dot_protos_dot_data__bundle__pb2.DESCRIPTOR,contrib_dot_coms_dot_protos_dot_broker__pb2.DESCRIPTOR,contrib_dot_control_dot_controller__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,contrib_dot_control_dot_clock__pb2.DESCRIPTOR,contrib_dot_control_dot_data__pb2.DESCRIPTOR,])




_INITPARAMS = _descriptor.Descriptor(
  name='InitParams',
  full_name='InitParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='domain', full_name='InitParams.domain', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strategy', full_name='InitParams.strategy', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='capital', full_name='InitParams.capital', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=347,
)


_UPDATEMESSAGE = _descriptor.Descriptor(
  name='UpdateMessage',
  full_name='UpdateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='UpdateMessage.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event', full_name='UpdateMessage.event', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='broker_state', full_name='UpdateMessage.broker_state', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=470,
)

_INITPARAMS.fields_by_name['domain'].message_type = contrib_dot_coms_dot_protos_dot_data__bundle__pb2._COMPOUNDDOMAINDEF
_UPDATEMESSAGE.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_UPDATEMESSAGE.fields_by_name['event'].enum_type = contrib_dot_control_dot_clock__pb2._EVENT
_UPDATEMESSAGE.fields_by_name['broker_state'].message_type = contrib_dot_coms_dot_protos_dot_broker__pb2._BROKERSTATE
DESCRIPTOR.message_types_by_name['InitParams'] = _INITPARAMS
DESCRIPTOR.message_types_by_name['UpdateMessage'] = _UPDATEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InitParams = _reflection.GeneratedProtocolMessageType('InitParams', (_message.Message,), dict(
  DESCRIPTOR = _INITPARAMS,
  __module__ = 'contrib.control.controllable_pb2'
  # @@protoc_insertion_point(class_scope:InitParams)
  ))
_sym_db.RegisterMessage(InitParams)

UpdateMessage = _reflection.GeneratedProtocolMessageType('UpdateMessage', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEMESSAGE,
  __module__ = 'contrib.control.controllable_pb2'
  # @@protoc_insertion_point(class_scope:UpdateMessage)
  ))
_sym_db.RegisterMessage(UpdateMessage)



_CONTROLLABLE = _descriptor.ServiceDescriptor(
  name='Controllable',
  full_name='Controllable',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=473,
  serialized_end=766,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateDataBundle',
    full_name='Controllable.UpdateDataBundle',
    index=0,
    containing_service=None,
    input_type=contrib_dot_control_dot_data__pb2._DATA,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateParameters',
    full_name='Controllable.UpdateParameters',
    index=1,
    containing_service=None,
    input_type=contrib_dot_control_dot_controller__pb2._PARAMETERSUPDATEMESSAGE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Initialize',
    full_name='Controllable.Initialize',
    index=2,
    containing_service=None,
    input_type=contrib_dot_control_dot_data__pb2._DATA,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='Controllable.Update',
    index=3,
    containing_service=None,
    input_type=contrib_dot_control_dot_data__pb2._DATA,
    output_type=contrib_dot_control_dot_data__pb2._DATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateCalendar',
    full_name='Controllable.UpdateCalendar',
    index=4,
    containing_service=None,
    input_type=contrib_dot_control_dot_data__pb2._DATA,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Stop',
    full_name='Controllable.Stop',
    index=5,
    containing_service=None,
    input_type=contrib_dot_control_dot_controller__pb2._STOPPARAMS,
    output_type=contrib_dot_control_dot_data__pb2._DATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTROLLABLE)

DESCRIPTOR.services_by_name['Controllable'] = _CONTROLLABLE

# @@protoc_insertion_point(module_scope)
