# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contrib/control/controllable.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from contrib.coms.protos import data_bundle_pb2 as contrib_dot_coms_dot_protos_dot_data__bundle__pb2
from contrib.coms.protos import broker_pb2 as contrib_dot_coms_dot_protos_dot_broker__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from contrib.control import clock_pb2 as contrib_dot_control_dot_clock__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='contrib/control/controllable.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\"contrib/control/controllable.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a%contrib/coms/protos/data_bundle.proto\x1a contrib/coms/protos/broker.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1b\x63ontrib/control/clock.proto\"v\n\nUpdateData\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\x05\x65vent\x18\x02 \x01(\x0e\x32\x06.Event\x12\"\n\x0c\x62roker_state\x18\x03 \x01(\x0b\x32\x0c.BrokerState2\xde\x01\n\x0c\x43ontrollable\x12\x34\n\x11ReceiveDataBundle\x12\x07.Bundle\x1a\x16.google.protobuf.Empty\x12-\n\x06Update\x12\x0b.UpdateData\x1a\x16.google.protobuf.Empty\x12;\n\x0eUpdateCalendar\x12\x11.CalendarMetadata\x1a\x16.google.protobuf.Empty\x12,\n\tGetDomain\x12\x16.google.protobuf.Empty\x1a\x07.Domainb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,contrib_dot_coms_dot_protos_dot_data__bundle__pb2.DESCRIPTOR,contrib_dot_coms_dot_protos_dot_broker__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,contrib_dot_control_dot_clock__pb2.DESCRIPTOR,])




_UPDATEDATA = _descriptor.Descriptor(
  name='UpdateData',
  full_name='UpdateData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='UpdateData.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event', full_name='UpdateData.event', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='broker_state', full_name='UpdateData.broker_state', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=320,
)

_UPDATEDATA.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_UPDATEDATA.fields_by_name['event'].enum_type = contrib_dot_control_dot_clock__pb2._EVENT
_UPDATEDATA.fields_by_name['broker_state'].message_type = contrib_dot_coms_dot_protos_dot_broker__pb2._BROKERSTATE
DESCRIPTOR.message_types_by_name['UpdateData'] = _UPDATEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateData = _reflection.GeneratedProtocolMessageType('UpdateData', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEDATA,
  __module__ = 'contrib.control.controllable_pb2'
  # @@protoc_insertion_point(class_scope:UpdateData)
  ))
_sym_db.RegisterMessage(UpdateData)



_CONTROLLABLE = _descriptor.ServiceDescriptor(
  name='Controllable',
  full_name='Controllable',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=323,
  serialized_end=545,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReceiveDataBundle',
    full_name='Controllable.ReceiveDataBundle',
    index=0,
    containing_service=None,
    input_type=contrib_dot_coms_dot_protos_dot_data__bundle__pb2._BUNDLE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='Controllable.Update',
    index=1,
    containing_service=None,
    input_type=_UPDATEDATA,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateCalendar',
    full_name='Controllable.UpdateCalendar',
    index=2,
    containing_service=None,
    input_type=contrib_dot_control_dot_clock__pb2._CALENDARMETADATA,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDomain',
    full_name='Controllable.GetDomain',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=contrib_dot_coms_dot_protos_dot_data__bundle__pb2._DOMAIN,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTROLLABLE)

DESCRIPTOR.services_by_name['Controllable'] = _CONTROLLABLE

# @@protoc_insertion_point(module_scope)
