# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from contrib.coms.protos import data_bundle_pb2 as contrib_dot_coms_dot_protos_dot_data__bundle__pb2
from contrib.control import clock_pb2 as contrib_dot_control_dot_clock__pb2
from contrib.control import controllable_pb2 as contrib_dot_control_dot_controllable__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ControllableStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ReceiveDataBundle = channel.unary_unary(
        '/Controllable/ReceiveDataBundle',
        request_serializer=contrib_dot_coms_dot_protos_dot_data__bundle__pb2.Bundle.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Update = channel.unary_unary(
        '/Controllable/Update',
        request_serializer=contrib_dot_control_dot_controllable__pb2.UpdateData.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.UpdateCalendar = channel.unary_unary(
        '/Controllable/UpdateCalendar',
        request_serializer=contrib_dot_control_dot_clock__pb2.CalendarMetadata.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.GetDomain = channel.unary_unary(
        '/Controllable/GetDomain',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=contrib_dot_coms_dot_protos_dot_data__bundle__pb2.Domain.FromString,
        )


class ControllableServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ReceiveDataBundle(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request, context):
    """rpc UpdateParameters (ParametersUpdateMessage) returns (google.protobuf.Empty);
    rpc Initialize (InitialParameters) returns (google.protobuf.Empty);
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateCalendar(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDomain(self, request, context):
    """gets the domain on which the strategy operates.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ControllableServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ReceiveDataBundle': grpc.unary_unary_rpc_method_handler(
          servicer.ReceiveDataBundle,
          request_deserializer=contrib_dot_coms_dot_protos_dot_data__bundle__pb2.Bundle.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=contrib_dot_control_dot_controllable__pb2.UpdateData.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'UpdateCalendar': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateCalendar,
          request_deserializer=contrib_dot_control_dot_clock__pb2.CalendarMetadata.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'GetDomain': grpc.unary_unary_rpc_method_handler(
          servicer.GetDomain,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=contrib_dot_coms_dot_protos_dot_data__bundle__pb2.Domain.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Controllable', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
