# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from protos import data_bundle_pb2 as protos_dot_data__bundle__pb2
from protos import data_pb2 as protos_dot_data__pb2
from protos import hub_pb2 as protos_dot_hub__pb2


class HubStub(object):
  """
  The environment is stored for the lifetime of the application.
  A strategy returned by GetStrategy cannot be modified. (It can only be ran or stopped)
  A strategy returned by ModifyStrategy returns a simulation environment. It can optionally
  be stopped if it is running in a paper env or live env.)
  This service stores timestamped version of each strategy, so that we could roll-back,
  to a previous version of an implementation.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Deploy = channel.stream_unary(
        '/Hub/Deploy',
        request_serializer=protos_dot_data__pb2.Data.SerializeToString,
        response_deserializer=protos_dot_hub__pb2.DeploymentReply.FromString,
        )
    self.New = channel.stream_stream(
        '/Hub/New',
        request_serializer=protos_dot_data__bundle__pb2.CompoundDomainDef.SerializeToString,
        response_deserializer=protos_dot_data__pb2.Data.FromString,
        )
    self.Modify = channel.unary_stream(
        '/Hub/Modify',
        request_serializer=protos_dot_hub__pb2.ModificationRequest.SerializeToString,
        response_deserializer=protos_dot_data__pb2.Data.FromString,
        )
    self.Push = channel.stream_unary(
        '/Hub/Push',
        request_serializer=protos_dot_data__pb2.Data.SerializeToString,
        response_deserializer=protos_dot_hub__pb2.DeploymentReply.FromString,
        )
    self.DeploymentStatus = channel.unary_stream(
        '/Hub/DeploymentStatus',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=protos_dot_hub__pb2.DeploymentStatusReply.FromString,
        )
    self.MountBroker = channel.unary_unary(
        '/Hub/MountBroker',
        request_serializer=protos_dot_hub__pb2.BrokerID.SerializeToString,
        response_deserializer=protos_dot_hub__pb2.MountStatus.FromString,
        )
    self.List = channel.unary_stream(
        '/Hub/List',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=protos_dot_data__pb2.Data.FromString,
        )


class HubServicer(object):
  """
  The environment is stored for the lifetime of the application.
  A strategy returned by GetStrategy cannot be modified. (It can only be ran or stopped)
  A strategy returned by ModifyStrategy returns a simulation environment. It can optionally
  be stopped if it is running in a paper env or live env.)
  This service stores timestamped version of each strategy, so that we could roll-back,
  to a previous version of an implementation.
  """

  def Deploy(self, request_iterator, context):
    """request a strategy deployment in a new environment (depending on the environment,
    some external actor might need to confirm (admin, user with the right credentials...))
    the input is the id of the strategy not data!!!!
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def New(self, request_iterator, context):
    """the client also sends a name as metadata...
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Modify(self, request, context):
    """adds a new version to the list of strategies
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Push(self, request_iterator, context):
    """pushes one or more strategies to the the hub...
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeploymentStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MountBroker(self, request, context):
    """mounts a broker to be used by the controllers. The broker is a service that must
    implement a certain interface... Note this method cannot be called by any user.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def List(self, request, context):
    """get a list of the strategies on the current branch
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HubServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Deploy': grpc.stream_unary_rpc_method_handler(
          servicer.Deploy,
          request_deserializer=protos_dot_data__pb2.Data.FromString,
          response_serializer=protos_dot_hub__pb2.DeploymentReply.SerializeToString,
      ),
      'New': grpc.stream_stream_rpc_method_handler(
          servicer.New,
          request_deserializer=protos_dot_data__bundle__pb2.CompoundDomainDef.FromString,
          response_serializer=protos_dot_data__pb2.Data.SerializeToString,
      ),
      'Modify': grpc.unary_stream_rpc_method_handler(
          servicer.Modify,
          request_deserializer=protos_dot_hub__pb2.ModificationRequest.FromString,
          response_serializer=protos_dot_data__pb2.Data.SerializeToString,
      ),
      'Push': grpc.stream_unary_rpc_method_handler(
          servicer.Push,
          request_deserializer=protos_dot_data__pb2.Data.FromString,
          response_serializer=protos_dot_hub__pb2.DeploymentReply.SerializeToString,
      ),
      'DeploymentStatus': grpc.unary_stream_rpc_method_handler(
          servicer.DeploymentStatus,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=protos_dot_hub__pb2.DeploymentStatusReply.SerializeToString,
      ),
      'MountBroker': grpc.unary_unary_rpc_method_handler(
          servicer.MountBroker,
          request_deserializer=protos_dot_hub__pb2.BrokerID.FromString,
          response_serializer=protos_dot_hub__pb2.MountStatus.SerializeToString,
      ),
      'List': grpc.unary_stream_rpc_method_handler(
          servicer.List,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=protos_dot_data__pb2.Data.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Hub', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
