# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/hub.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import data_bundle_pb2 as protos_dot_data__bundle__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from protos import data_pb2 as protos_dot_data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/hub.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10protos/hub.proto\x1a\x18protos/data_bundle.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x11protos/data.proto\"\x0e\n\x0c\x46\x65tchRequest\"L\n\x11NavigationRequest\x12\x13\n\x0bstart_point\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x11\n\tselection\x18\x03 \x01(\t\")\n\x0f\x44\x65ploymentReply\x12\x16\n\x0e\x63ontroller_url\x18\x01 \x01(\t\":\n\x11\x44\x65ploymentRequest\x12\x13\n\x0bstrategy_id\x18\x01 \x03(\t\x12\x10\n\x08\x65nv_type\x18\x02 \x01(\t\"<\n\x15\x44\x65ploymentStatusReply\x12\x13\n\x0bstrategy_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"%\n\x08\x42rokerID\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"\r\n\x0bMountStatus\"\x0f\n\rAdditionReply\"@\n\x13ModificationRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0c\n\x04stop\x18\x03 \x01(\x08\"*\n\nStrategyID\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x65nv_type\x18\x02 \x01(\t\";\n\x0fStrategyRequest\x12\x17\n\x02id\x18\x01 \x01(\x0b\x32\x0b.StrategyID\x12\x0f\n\x07version\x18\x02 \x01(\t\")\n\x06\x46ilter\x12\x10\n\x08\x65nv_type\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\"(\n\x08Strategy\x12\x10\n\x08strategy\x18\x01 \x01(\x0c\x12\n\n\x02id\x18\x02 \x01(\t\",\n\x0bStrategySet\x12\x1d\n\nstrategies\x18\x01 \x03(\x0b\x32\t.Strategy2\xb3\x02\n\x03Hub\x12#\n\x06\x44\x65ploy\x12\x05.Data\x1a\x10.DeploymentReply(\x01\x12$\n\x03New\x12\x12.CompoundDomainDef\x1a\x05.Data(\x01\x30\x01\x12\'\n\x06Modify\x12\x14.ModificationRequest\x1a\x05.Data0\x01\x12!\n\x04Push\x12\x05.Data\x1a\x10.DeploymentReply(\x01\x12\x44\n\x10\x44\x65ploymentStatus\x12\x16.google.protobuf.Empty\x1a\x16.DeploymentStatusReply0\x01\x12&\n\x0bMountBroker\x12\t.BrokerID\x1a\x0c.MountStatus\x12\'\n\x04List\x12\x16.google.protobuf.Empty\x1a\x05.Data0\x01\x62\x06proto3')
  ,
  dependencies=[protos_dot_data__bundle__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,protos_dot_data__pb2.DESCRIPTOR,])




_FETCHREQUEST = _descriptor.Descriptor(
  name='FetchRequest',
  full_name='FetchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=108,
)


_NAVIGATIONREQUEST = _descriptor.Descriptor(
  name='NavigationRequest',
  full_name='NavigationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_point', full_name='NavigationRequest.start_point', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='NavigationRequest.command', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='selection', full_name='NavigationRequest.selection', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=186,
)


_DEPLOYMENTREPLY = _descriptor.Descriptor(
  name='DeploymentReply',
  full_name='DeploymentReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='controller_url', full_name='DeploymentReply.controller_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=229,
)


_DEPLOYMENTREQUEST = _descriptor.Descriptor(
  name='DeploymentRequest',
  full_name='DeploymentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='strategy_id', full_name='DeploymentRequest.strategy_id', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='env_type', full_name='DeploymentRequest.env_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=289,
)


_DEPLOYMENTSTATUSREPLY = _descriptor.Descriptor(
  name='DeploymentStatusReply',
  full_name='DeploymentStatusReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='strategy_id', full_name='DeploymentStatusReply.strategy_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='DeploymentStatusReply.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=351,
)


_BROKERID = _descriptor.Descriptor(
  name='BrokerID',
  full_name='BrokerID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='BrokerID.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='BrokerID.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=390,
)


_MOUNTSTATUS = _descriptor.Descriptor(
  name='MountStatus',
  full_name='MountStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=405,
)


_ADDITIONREPLY = _descriptor.Descriptor(
  name='AdditionReply',
  full_name='AdditionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=422,
)


_MODIFICATIONREQUEST = _descriptor.Descriptor(
  name='ModificationRequest',
  full_name='ModificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ModificationRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='ModificationRequest.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stop', full_name='ModificationRequest.stop', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=488,
)


_STRATEGYID = _descriptor.Descriptor(
  name='StrategyID',
  full_name='StrategyID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='StrategyID.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='env_type', full_name='StrategyID.env_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=490,
  serialized_end=532,
)


_STRATEGYREQUEST = _descriptor.Descriptor(
  name='StrategyRequest',
  full_name='StrategyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='StrategyRequest.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='StrategyRequest.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=534,
  serialized_end=593,
)


_FILTER = _descriptor.Descriptor(
  name='Filter',
  full_name='Filter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='env_type', full_name='Filter.env_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='Filter.state', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=595,
  serialized_end=636,
)


_STRATEGY = _descriptor.Descriptor(
  name='Strategy',
  full_name='Strategy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='strategy', full_name='Strategy.strategy', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='Strategy.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=638,
  serialized_end=678,
)


_STRATEGYSET = _descriptor.Descriptor(
  name='StrategySet',
  full_name='StrategySet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='strategies', full_name='StrategySet.strategies', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=680,
  serialized_end=724,
)

_STRATEGYREQUEST.fields_by_name['id'].message_type = _STRATEGYID
_STRATEGYSET.fields_by_name['strategies'].message_type = _STRATEGY
DESCRIPTOR.message_types_by_name['FetchRequest'] = _FETCHREQUEST
DESCRIPTOR.message_types_by_name['NavigationRequest'] = _NAVIGATIONREQUEST
DESCRIPTOR.message_types_by_name['DeploymentReply'] = _DEPLOYMENTREPLY
DESCRIPTOR.message_types_by_name['DeploymentRequest'] = _DEPLOYMENTREQUEST
DESCRIPTOR.message_types_by_name['DeploymentStatusReply'] = _DEPLOYMENTSTATUSREPLY
DESCRIPTOR.message_types_by_name['BrokerID'] = _BROKERID
DESCRIPTOR.message_types_by_name['MountStatus'] = _MOUNTSTATUS
DESCRIPTOR.message_types_by_name['AdditionReply'] = _ADDITIONREPLY
DESCRIPTOR.message_types_by_name['ModificationRequest'] = _MODIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['StrategyID'] = _STRATEGYID
DESCRIPTOR.message_types_by_name['StrategyRequest'] = _STRATEGYREQUEST
DESCRIPTOR.message_types_by_name['Filter'] = _FILTER
DESCRIPTOR.message_types_by_name['Strategy'] = _STRATEGY
DESCRIPTOR.message_types_by_name['StrategySet'] = _STRATEGYSET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FetchRequest = _reflection.GeneratedProtocolMessageType('FetchRequest', (_message.Message,), dict(
  DESCRIPTOR = _FETCHREQUEST,
  __module__ = 'protos.hub_pb2'
  # @@protoc_insertion_point(class_scope:FetchRequest)
  ))
_sym_db.RegisterMessage(FetchRequest)

NavigationRequest = _reflection.GeneratedProtocolMessageType('NavigationRequest', (_message.Message,), dict(
  DESCRIPTOR = _NAVIGATIONREQUEST,
  __module__ = 'protos.hub_pb2'
  # @@protoc_insertion_point(class_scope:NavigationRequest)
  ))
_sym_db.RegisterMessage(NavigationRequest)

DeploymentReply = _reflection.GeneratedProtocolMessageType('DeploymentReply', (_message.Message,), dict(
  DESCRIPTOR = _DEPLOYMENTREPLY,
  __module__ = 'protos.hub_pb2'
  # @@protoc_insertion_point(class_scope:DeploymentReply)
  ))
_sym_db.RegisterMessage(DeploymentReply)

DeploymentRequest = _reflection.GeneratedProtocolMessageType('DeploymentRequest', (_message.Message,), dict(
  DESCRIPTOR = _DEPLOYMENTREQUEST,
  __module__ = 'protos.hub_pb2'
  # @@protoc_insertion_point(class_scope:DeploymentRequest)
  ))
_sym_db.RegisterMessage(DeploymentRequest)

DeploymentStatusReply = _reflection.GeneratedProtocolMessageType('DeploymentStatusReply', (_message.Message,), dict(
  DESCRIPTOR = _DEPLOYMENTSTATUSREPLY,
  __module__ = 'protos.hub_pb2'
  # @@protoc_insertion_point(class_scope:DeploymentStatusReply)
  ))
_sym_db.RegisterMessage(DeploymentStatusReply)

BrokerID = _reflection.GeneratedProtocolMessageType('BrokerID', (_message.Message,), dict(
  DESCRIPTOR = _BROKERID,
  __module__ = 'protos.hub_pb2'
  # @@protoc_insertion_point(class_scope:BrokerID)
  ))
_sym_db.RegisterMessage(BrokerID)

MountStatus = _reflection.GeneratedProtocolMessageType('MountStatus', (_message.Message,), dict(
  DESCRIPTOR = _MOUNTSTATUS,
  __module__ = 'protos.hub_pb2'
  # @@protoc_insertion_point(class_scope:MountStatus)
  ))
_sym_db.RegisterMessage(MountStatus)

AdditionReply = _reflection.GeneratedProtocolMessageType('AdditionReply', (_message.Message,), dict(
  DESCRIPTOR = _ADDITIONREPLY,
  __module__ = 'protos.hub_pb2'
  # @@protoc_insertion_point(class_scope:AdditionReply)
  ))
_sym_db.RegisterMessage(AdditionReply)

ModificationRequest = _reflection.GeneratedProtocolMessageType('ModificationRequest', (_message.Message,), dict(
  DESCRIPTOR = _MODIFICATIONREQUEST,
  __module__ = 'protos.hub_pb2'
  # @@protoc_insertion_point(class_scope:ModificationRequest)
  ))
_sym_db.RegisterMessage(ModificationRequest)

StrategyID = _reflection.GeneratedProtocolMessageType('StrategyID', (_message.Message,), dict(
  DESCRIPTOR = _STRATEGYID,
  __module__ = 'protos.hub_pb2'
  # @@protoc_insertion_point(class_scope:StrategyID)
  ))
_sym_db.RegisterMessage(StrategyID)

StrategyRequest = _reflection.GeneratedProtocolMessageType('StrategyRequest', (_message.Message,), dict(
  DESCRIPTOR = _STRATEGYREQUEST,
  __module__ = 'protos.hub_pb2'
  # @@protoc_insertion_point(class_scope:StrategyRequest)
  ))
_sym_db.RegisterMessage(StrategyRequest)

Filter = _reflection.GeneratedProtocolMessageType('Filter', (_message.Message,), dict(
  DESCRIPTOR = _FILTER,
  __module__ = 'protos.hub_pb2'
  # @@protoc_insertion_point(class_scope:Filter)
  ))
_sym_db.RegisterMessage(Filter)

Strategy = _reflection.GeneratedProtocolMessageType('Strategy', (_message.Message,), dict(
  DESCRIPTOR = _STRATEGY,
  __module__ = 'protos.hub_pb2'
  # @@protoc_insertion_point(class_scope:Strategy)
  ))
_sym_db.RegisterMessage(Strategy)

StrategySet = _reflection.GeneratedProtocolMessageType('StrategySet', (_message.Message,), dict(
  DESCRIPTOR = _STRATEGYSET,
  __module__ = 'protos.hub_pb2'
  # @@protoc_insertion_point(class_scope:StrategySet)
  ))
_sym_db.RegisterMessage(StrategySet)



_HUB = _descriptor.ServiceDescriptor(
  name='Hub',
  full_name='Hub',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=727,
  serialized_end=1034,
  methods=[
  _descriptor.MethodDescriptor(
    name='Deploy',
    full_name='Hub.Deploy',
    index=0,
    containing_service=None,
    input_type=protos_dot_data__pb2._DATA,
    output_type=_DEPLOYMENTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='New',
    full_name='Hub.New',
    index=1,
    containing_service=None,
    input_type=protos_dot_data__bundle__pb2._COMPOUNDDOMAINDEF,
    output_type=protos_dot_data__pb2._DATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Modify',
    full_name='Hub.Modify',
    index=2,
    containing_service=None,
    input_type=_MODIFICATIONREQUEST,
    output_type=protos_dot_data__pb2._DATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Push',
    full_name='Hub.Push',
    index=3,
    containing_service=None,
    input_type=protos_dot_data__pb2._DATA,
    output_type=_DEPLOYMENTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeploymentStatus',
    full_name='Hub.DeploymentStatus',
    index=4,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_DEPLOYMENTSTATUSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='MountBroker',
    full_name='Hub.MountBroker',
    index=5,
    containing_service=None,
    input_type=_BROKERID,
    output_type=_MOUNTSTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='List',
    full_name='Hub.List',
    index=6,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=protos_dot_data__pb2._DATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HUB)

DESCRIPTOR.services_by_name['Hub'] = _HUB

# @@protoc_insertion_point(module_scope)
